### ISSUE TITLE
Code Suggestions and Conventions

### ISSUE THREAD

**Issue by Sparky200** [Railroad-Team/Modding-IDE#28]
Wanted to compile a list of a few parts I find a little... concerning.... It's whatever, but these are mostly following Java's currently accepted conventions

**Why JavaFX?**
This may have already been considered, but I do suggest looking into Swing as well. They both have their pros and cons, but I wanted to suggest looking into it. (did you know: IntelliJ uses Swing 😛)

**Package Name Capitalization**
The convention for package names is `lowercase`. In C#, namespaces (the equivalent) is `PascalCase`. It just strikes as odd that these packages use `camelCase` for their name. I'll make a PR later and add this to it.

**Field Name Convention**
I haven't gone through all of the code so far, but I saw this with `Railroad#DRPManager`. In addition, this is able to be converted to a local field (thank you, IntelliJ). I'll clean this up in a PR in a bit.

**Non-useful Methods**
This could be as placeholders or even simple tests, but I'm referring to `DownloadUtils.DownloadTask#failed()` and `DownloadUtils.DownloadTask#succeeded()`. Once again, as I have not gone through the entire code, I do not know if there are more.

**JavaDocs**
It's hard to understand what things are doing when you don't document them, could you write docs when you are developing? It makes it easier on others.

A few Java conventions:
```
Java Conventions

Package Names: lowercase
Class Names: PascalCase (UpperCamelCase)
Method Names: camelCase
Constant Names: UPPER_SNAKE_CASE
Attribute Names: camelCase
Annotations: @PascalCase

Root Package Convention: domainending.domainname.project


Variable Naming Conventions

Don't create singular letter variables as it's confusing to others (and yourself later down the line). A few exceptions to this conventions are coordinates (int x = 10, y = 20;) and key value pairs (i, v)
```

If I missed anything, please let me know! I will submit a PR and link it soon once I finish going through the code. The project seems promising, so hopefully I'm of some help 😄

**Comment by DaRealTurtyWurty** [comment]
I agree with all of these. So far everything has been a little rushed for some unknown reason, so hopefully, it will go forward cleaner. In terms of using Java Swing, JavaFX is basically just a better, less clunky swing so we are not going to be using swing.

Are you going to make the PR? Or do we want me or someone else to fix this?

**Comment by Sparky200** [comment]
> Are you going to make the PR? Or do we want me or someone else to fix this?
Sorry, had something I needed to do. The PR is made.

> However, in terms of using Java Swing, JavaFX is basically just a better, less clunky swing so we are not going to be using swing.
👍 Just wanted to give something that's something to think about.

**Comment by DaRealTurtyWurty** [comment]
All added in https://github.com/Railroad-Team/Modding-IDE/commit/7c33b690b612376a491050eaba6fb5aefcd5e745
